[package]
name = "mcserv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnbt = "2.2.0"
polling = "2.2.0"

env_logger = "0.9.0"
log = "0.4.17"
serde_json = "1.0.82"
local-ip-address = "0.4.6"
